apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-2 # 您可以更改此名稱
spec:
  # --- 重要 ---
  # 這是您的第二個後端設定。
  # 您必須將它們替換為您第二個後端的實際設定資訊。
  version: 1
  storageDriverName: ontap-san # 或 ontap-nas 等
  managementLIF: 192.168.2.100 # 範例 IP，請替換為您的第二個 NetApp 管理 IP
  dataLIF: 192.168.2.101 # 範例 IP，如果需要請替換
  svm: svm_name_2 # 範例 SVM 名稱，請替換為您的第二個 SVM
  username: vsadmin # 範例使用者名稱，請替換為您的使用者名稱
  password: your_password # 範例密碼，請替換為您的密碼

  # 這個標籤必須與 sc.yaml 中的 selector 和第一個後端的標籤相同。
  labels:
    tier: "es-data"

  # --- 預留位置區塊結束 ---
